const palette = {
  wine: "#7B1E2D",
  wineDark: "#5C1521",
  terracotta: "#C4513C",
  terracottaLight: "#D4735F",
  gold: "#C9933A",
  goldLight: "#E8B85A",
  cream: "#F5EEE4",
  creamDark: "#EDE3D5",
  inkDark: "#1A0A05",
  inkMid: "#4A2E24",
  inkLight: "#7A5B50",
  white: "#FFFFFF",
  success: "#2E7D52",
  error: "#B03030",
  errorLight: "#FFE8E8",
  successLight: "#E8F5EE",
};

export default {
  palette,
  light: {
    background: palette.cream,
    backgroundSecondary: palette.creamDark,
    card: palette.white,
    text: palette.inkDark,
    textSecondary: palette.inkLight,
    textMuted: "#A08878",
    tint: palette.wine,
    accent: palette.gold,
    tabIconDefault: "#B09080",
    tabIconSelected: palette.wine,
    border: "#E0D0C4",
    separator: "#DDD0C0",
  },
  dark: {
    background: "#1A0A05",
    backgroundSecondary: "#2D1810",
    card: "#3A2018",
    text: palette.cream,
    textSecondary: "#C8B4A8",
    textMuted: "#7A6058",
    tint: palette.terracottaLight,
    accent: palette.goldLight,
    tabIconDefault: "#7A6058",
    tabIconSelected: palette.terracottaLight,
    border: "#4A2E24",
    separator: "#3A2018",
  },
};
